class TEMPLATE_TYPE:
    PROJECT_TEMPLATE = '1'
    PROGRAM_TEMPLATE = '2'
    OBSERVATION_TEMPLATE = '3'
    SURVEY_TEMPLATE = '4'
    OBSERVATION_WITH_RUBRICS_TEMPLATE = '5'
    OBSERVATION_LED_IMPROVEMENT_TEMPLATE = '6'


class SHEET_NAME:
    PROJECT_UPLOAD = '1'
    TASK_UPLOAD = '2'
    CERTIFICATE_DETAILS = '3'
    SURVEY_DETAILS = '4'
    SURVEY_QUESTIONS = '5'
    PROGRAM_DETAILS = '6'
    RESOURCE_DETAILS = '7'
    PROGRAM_MANAGER_DETAILS = '8'


class TEMPLATE_STATUS:
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'
    ARCHIVED = 'ARCHIVED'
